### ISSUE TITLE
Coupling of org.avuna.httpd.AvunaHTTPD

### ISSUE THREAD

**Issue by DarkStorm652** [JavaProphet/Avuna-HTTPD#2]
That class has way too many separate concerns mixed into one. Extremely coupled with no dependency injection at all. :fearful:

**Comment by Protryon** [comment]
You are very right. I haphazardly dropped anything I was unsure of in there, and that'll be changed soon.

**Comment by DarkStorm652** [comment]
But the issue persists!

**Comment by Protryon** [comment]
Just closing it, not out of my Todo list. :)
